services:
  cobalt-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cobalt-api
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      API_URL: "https://api-dl.q0wqex.ru/"
      API_PORT: "9000"
      API_LISTEN_ADDRESS: "0.0.0.0"
      CUSTOM_INNERTUBE_CLIENT: "IOS"
      COOKIE_PATH: "/cookies.json"
      DURATION_LIMIT: "10800"
    volumes:
      - ./cookies.json:/cookies.json:ro

  cobalt-web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        WEB_HOST: "dl.q0wqex.ru"
        WEB_DEFAULT_API: "https://api-dl.q0wqex.ru"
    container_name: cobalt-web
    restart: conscience
    restart: unless-stopped
    ports:
      - "127.0.0.1:9001:80"
