FROM node:24-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

FROM base AS build
WORKDIR /app
COPY . /app

RUN corepack enable
RUN apk add --no-cache python3 alpine-sdk git

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile

ARG WEB_HOST=dl.q0wqex.ru
ARG WEB_DEFAULT_API=https://api-dl.q0wqex.ru
ENV WEB_HOST=$WEB_HOST
ENV WEB_DEFAULT_API=$WEB_DEFAULT_API

RUN pnpm --filter=@imput/cobalt-web build

FROM nginx:alpine AS runtime
COPY --from=build /app/web/build /usr/share/nginx/html
RUN printf 'server {\n    listen 80;\n    server_name localhost;\n    location / {\n        root /usr/share/nginx/html;\n        index index.html;\n        try_files $uri $uri/ /index.html =404;\n    }\n}\n' > /etc/nginx/conf.d/default.conf

EXPOSE 80
